In [2]:
import numpy as np

####numpy array

In [3]:
myList=[1,2,3,4,5]
type(myList)

list

In [4]:
arr=np.array(myList)
arr

array([1, 2, 3, 4, 5])

In [5]:
matrixList=[[1,2,3,4],[10,20,30,40],[50,60,70,80]]
matrixArray=np.array(matrixList)
print(matrixArray)

[[ 1  2  3  4]
 [10 20 30 40]
 [50 60 70 80]]


####arange

In [6]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

zeros

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

linspace

In [15]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

eye

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])