In [2]:
import numpy as np

In [3]:
myList=[[1,2,3,4],[5,6,7,8],[9,3,4,5]]
np.array(myList)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 3, 4, 5]])

In [15]:
myList

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 3, 4, 5]]

In [4]:
matrix=np.array(myList)
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 3, 4, 5]])

In [27]:
matrix[1:,1:3]

array([[6, 7],
       [3, 4]])

In [19]:
matrix[1][2]


7

In [7]:
matrix[1,2]

7

In [8]:
matrix[1:,2]

array([7, 4])

In [9]:
matrix[0:,2:]

array([[3, 4],
       [7, 8],
       [4, 5]])

In [10]:
matrix[1:,1:3]

array([[6, 7],
       [3, 4]])

In [11]:
newList=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [12]:
arr=np.array(newList)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
arr[[1]]
#arr[[1]] demek 1.satırı al gel demek

array([[4, 5, 6]])

In [14]:
arr[[3,2,0]]

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 1,  2,  3]])