In [2]:
import numpy as np

In [3]:
myArr=np.arange(0,15)


In [4]:
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
myArr[3:5]

array([3, 4])

In [6]:
myArr[3:8]=-5

In [7]:
myArr

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr=np.arange(0,24)

In [20]:
anotherArr=arr[9:24]
anotherArr

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700,
       700, 700])

In [10]:
anotherArr[:]=700

In [11]:
anotherArr

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700,
       700, 700])

In [12]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 700, 700, 700, 700,
       700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [13]:
exArr=arr.copy()

In [14]:
exArr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 700, 700, 700, 700,
       700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [15]:
exArr[:]=800

In [21]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 700, 700, 700, 700,
       700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [22]:
exArr

array([800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800,
       800, 800, 800, 800, 800, 800, 800, 800, 800, 800, 800])