In [2]:
import numpy as np

In [3]:
myNumArr=np.arange(30)

In [4]:
myNumArr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [5]:
myNumArr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
myNumArr.max()

29

In [7]:
np.max(myNumArr)

0

In [15]:
myNumArr.min()

0

In [16]:
np.min(myNumArr)

0

In [17]:
myNumArr.argmax()
#max elemanın indexini döner

29

In [10]:
myNumArr.argmin()

0

In [11]:
myNumArr.shape

(30,)

In [19]:
myNumArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
myReshapeArr=myNumArr.reshape(5,6)
print(myReshapeArr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [14]:
myReshapeArr.shape

(5, 6)