In [34]:
import numpy as np

In [35]:
np.random.random(5)
#0 ile 1 arası 1 dahil değil float sayılar üretir

array([0.4507565 , 0.76022858, 0.41272534, 0.61624352, 0.476006  ])

In [36]:
np.random.random((3,3))
#0 ile 1 arası 1 dahil değil float sayılar üretir

array([[0.47085449, 0.30708794, 0.22948055],
       [0.38507809, 0.88550375, 0.0398765 ],
       [0.29018762, 0.60634746, 0.99633518]])

In [37]:
print(np.random.randn(7))
type(np.random.randn(3))


[-0.70823342  0.96211353  0.39515811  0.23467267  1.40250197 -0.66339531
  0.47267282]


numpy.ndarray

In [38]:
np.random.randn(8)

array([ 0.23828723,  1.9235574 ,  0.52846337, -3.42474751,  0.31259099,
       -0.98284038,  1.48102165, -0.49133293])

In [39]:
np.random.randn(2,2)

array([[ 0.30452982, -0.88865688],
       [ 0.73780123, -0.622318  ]])

In [40]:
np.random.randint(4,10)

8

In [41]:
np.random.randint(1,100,3)

array([99, 15, 94])

In [42]:
np.random.randint(1,10,size=(2,2))

array([[4, 4],
       [6, 7]])

In [43]:
myNumpyArr=np.arange(30)
print(myNumpyArr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [44]:
myRandomArr=np.random.randint(0,40,6)
print(myRandomArr)

[34 29 11 21  2 22]
